### ISSUE TITLE
Progress might lead to the android.os.DeadObjectException in android

### ISSUE THREAD

**Issue by opp100** [oblador/react-native-progress#28]
Hey there,

During I debug the react native application, I find out if the progress set there quite long, it will lead the some porblem as the follow shows. I don't have any enough technic to solve it. Can anyone help me?
```
W/WindowAnimator: Failed to dispatch window animation state change.
                                                 android.os.DeadObjectException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:503)
                                                     at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                     at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                     at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                     at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                     at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.os.HandlerThread.run(HandlerThread.java:61)
                                                     at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by SteffeyDev** [comment]
I am getting the same version on the latest version of RN and react-native-progress
